In [3]:
import pandas as pd

In [4]:
tweets = pd.read_excel("unique_tweets.xlsx")

In [5]:
import re
import emoji
from typing import List

In [6]:
tweets.sample(4)

,Unnamed: 0,id,tweet_created_at,text,user,bio,location,hashtags,user_mentions,in_reply,...,statuses_count,coordinates,is_quote_status,retweet_count,retweeted,lang,source,place,kwd,run_date
33291,6584,1526974660084219904,2022-05-18 17:15:03+00:00,हेटौंडामा मतपत्रमा भेटियो ‘नो भोट’ https://t.c...,UjyaloNepNews,बिश्वभरिका नेपाली ताजा खबरहरु एकै ठाउँमा ।,NaN,[],0,NaN,...,252504,NaN,False,0,False,ne,Ujyalo Nepal News,NaN,भोट,2022-05-18 16:56:17
51191,6274,1525306965815184896,2022-05-14 02:48:14+00:00,@GunarajUpadhya2 भाग खोज्नेहरु एमाले हुन सक्दै...,sagunbaba,सादा जिवन उच्च बिचार । आफु एकछाक खाएर अरुलाई २...,"Minnesota, USA",[],1,1.525159e+18,...,13631,NaN,False,0,False,ne,Twitter for iPhone,NaN,एमाले,2022-05-14 02:41:31
75780,3048,1522201555826778112,2022-05-05 13:08:26+00:00,नेपाल नागरिक अभियानको प्रतिवद्धता सार्वजनिक ht...,gothalokhabar,Subtle News on Digital World,"Putalisadak-29, Kathmandu",[],0,NaN,...,15419,NaN,False,0,False,ne,Twitter Web App,NaN,नेपाल,2022-05-05 12:58:07
14551,2772,1593725717681881088,2022-11-18 21:59:55+00:00,गठबन्धन 😀 https://t.co/tkYFvpb3Ok,Bsnt_Dhakal,A happy soul.,"California, USA",[],1,NaN,...,15195,NaN,False,8,False,ne,Twitter for iPhone,NaN,गठबन्धन,2022-11-19 01:15:28

In [7]:
tweets.columns

Index(['Unnamed: 0', 'id', 'tweet_created_at', 'text', 'user', 'bio',
       'location', 'hashtags', 'user_mentions', 'in_reply', 'protected',
       'followers_count', 'friends_count', 'listed_count', 'created_at',
       'favourites_count', 'geo_enabled', 'verified', 'statuses_count',
       'coordinates', 'is_quote_status', 'retweet_count', 'retweeted', 'lang',
       'source', 'place', 'kwd', 'run_date'],
      dtype='str')

In [8]:
tweets_sel = tweets[['id', 'text', 'kwd', 'lang']]

In [9]:
tweets_sel.head()

,id,text,kwd,lang
0,1601363673259290880,@thakurkc @mayor_harka हर्कराज साम्पाङ बालेन श...,जनप्रतिनिधि,ne
1,1601226348013707008,@KanakManiDixit @Himal_Khabar अब नयाँ जनप्रतिन...,जनप्रतिनिधि,ne
2,1601225158538117120,@damasebijaya च्याखे थापेर करारका जनप्रतिनिधिन...,जनप्रतिनिधि,ne
3,1601130318731259904,अहिले सत्तारुढ र एमाले दुवै गठबन्धनका नेताहरू ...,सत्तारुढ,ne
4,1601069274998504960,सत्तारुढ भारतीय जनता पार्टीको गुजरातमा ऐतिहासि...,सत्तारुढ,ne

# Only need id, text , kwd , lang

In [10]:
import glob

In [11]:
files = glob.glob("Label/*.xlsx")

In [12]:
files

['Label\\0_to_8897.xlsx',
 'Label\\17794_to_26691.xlsx',
 'Label\\26691_to_35588.xlsx',
 'Label\\35588_to_44485.xlsx',
 'Label\\44485_to_53382.xlsx',
 'Label\\53382_to_62279.xlsx',
 'Label\\62279_to_71176.xlsx',
 'Label\\71176_to_80073.xlsx',
 'Label\\80073_to_88973.xlsx',
 'Label\\8897_to_17794.xlsx']

In [13]:
labels = pd.concat([pd.read_excel(f) for f in files],ignore_index = True)

In [14]:
labels = labels.loc[:, ~labels.columns.str.contains("^Unnamed")]
labels = labels.drop(columns=["text"], errors="ignore")

In [15]:
labels.info()

<class 'pandas.DataFrame'>
RangeIndex: 88973 entries, 0 to 88972
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      88973 non-null  int64
 1   label   88911 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 1.4 MB

In [16]:
labels.sample(3)

                        id  label
50248  1524357077040197888    1.0
66881  1522201764266594048    2.0
11455  1587449880712457984    2.0

In [17]:
data = tweets_sel.merge(labels, on = "id")

In [18]:
data.sample(5)

,id,text,kwd,lang,label
20435,1587291188612186112,"हिजो का दिनमा काग्रेस,कम्युनिस्ट,राप्रपा भन्दै...",राप्रपा,ne,2.0
84899,1521061293591269120,मतदाताको पाउमा हजारकाे नोट राखेर भोट माग्दै मे...,कांग्रेस,ne,1.0
57651,1525131095682842880,शान्तिपूर्ण र उत्साहजनकरूपमा मतदान सम्पन्न : न...,निर्वाचन,ne,1.0
47814,1525338944405004032,#prasiddhaElectionUpdate\n\nभक्तपुरको सूर्यविन...,नेपाल,ne,1.0
2351,1597984924690444032,@AcharyaSarmila व्यापारी जे जस्तो भएपनि पहिले ...,सांसद,ne,1.0

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 88973 entries, 0 to 88972
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      88973 non-null  int64
 1   text    88972 non-null  str
 2   kwd     88973 non-null  str
 3   lang    88973 non-null  str
 4   label   88911 non-null  float64
dtypes: float64(1), int64(1), str(3)
memory usage: 34.2 MB

In [20]:
# Delete ALL rows with any missing values (including the text column)
data = data.dropna()

In [21]:
data.info()

<class 'pandas.DataFrame'>
Index: 88910 entries, 0 to 88972
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      88910 non-null  int64
 1   text    88910 non-null  str
 2   kwd     88910 non-null  str
 3   lang    88910 non-null  str
 4   label   88910 non-null  float64
dtypes: float64(1), int64(1), str(3)
memory usage: 34.9 MB

In [22]:
data["label"].value_counts()

label
1.0     52689
2.0     30229
0.0      5375
3.0       616
11.0        1
Name: count, dtype: int64

In [23]:
# Keep only rows where label is 1 or 2
data = data[data['label'].isin([1.0, 2.0])]

# Optional: check new label counts
print(data['label'].value_counts())

label
1.0    52689
2.0    30229
Name: count, dtype: int64

In [24]:
data.sample(5)

,id,text,kwd,lang,label
46051,1525358348832494080,पचरौता नगरपालिका बाहेक बारा जिल्लामा शान्तिपूर...,नगरपालिका,ne,1.0
36117,1526591606379659008,हाम्रो वडामा पहिले काङ्रेसले ८००+ मत अन्तरले ए...,एमाले,ne,2.0
11999,1591269971963044096,@dambarkhatiwoda देशकाे मायागर्नेहरु प्रतिगामी...,अग्रगामी,ne,2.0
60771,1521679919058673920,शेर बहादुरले आज एउटा साथीको उम्मेदवारी खरानी ब...,उम्मेदवारी,ne,2.0
38770,1523623090177342976,"एमालेका उम्मेदवारको मृत्यु, श्रीमतीले दिइन उम्...",उम्मेदवारी,ne,2.0

In [25]:
data = data[['text', 'label']]

# preview
print(data.head())

                                                text  label
0  @thakurkc @mayor_harka हर्कराज साम्पाङ बालेन श...    2.0
1  @KanakManiDixit @Himal_Khabar अब नयाँ जनप्रतिन...    2.0
2  @damasebijaya च्याखे थापेर करारका जनप्रतिनिधिन...    2.0
3  अहिले सत्तारुढ र एमाले दुवै गठबन्धनका नेताहरू ...    2.0
5  सबै क्षेत्रमा सबै खराब ब्यक्तिहरु छैनन तर जो ख...    2.0

In [26]:
data.shape

(82918, 2)

In [27]:
data.info()

<class 'pandas.DataFrame'>
Index: 82918 entries, 0 to 88972
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    82918 non-null  str
 1   label   82918 non-null  float64
dtypes: float64(1), str(1)
memory usage: 29.1 MB

# Data cleaning

In [32]:
import re
import os
import json
import unicodedata
import pandas as pd
import numpy as np
from typing import List

class DataHandler:
    def __init__(self, root: str,
                 file_ext: str = "xlsx",
                 old_vocab: str = None,
                 min_count: int = 200,
                 max_word_len: int = 20, 
                 min_word_needed: int = 3):
        
        self.root         = root
        self.file_ext     = file_ext
        self.vocab        = {}
        self.old_vocab_path = old_vocab
        self.min_word_needed = min_word_needed
        self.filter_words = None
        self.min_count    = min_count
        self.max_word_len = max_word_len

        if old_vocab is not None:
            with open(old_vocab) as fp:
                self.vocab = json.load(fp)
                less_freq_words = [k for k, v in self.vocab.items() if v < min_count]
                huge_words      = [k for k in self.vocab.keys() if len(k) > max_word_len]
                self.filter_words = less_freq_words + huge_words
                self.vocab = {k: v for k, v in self.vocab.items() 
                              if k not in self.filter_words}

    # ── File Reader ───────────────────────────────────────────────────────────

    def read_files(self, number_of_files: int = 10):
        all_filenames = [
            f for f in os.listdir(self.root)
            if f.split(".")[-1] == self.file_ext
        ][:number_of_files]

        combined = pd.concat([
            pd.read_excel(os.path.join(self.root, f)) for f in all_filenames
        ])

        # Keep only text and label columns
        self.data = combined[['text', 'label']].copy()
        self.data = self.data.dropna(subset=['text', 'label'])
        self.data = self.data.reset_index(drop=True)

        print(f"Read {len(all_filenames)} files. Total rows: {len(self.data)}")
        print(f"Label Counts:\n{self.data['label'].value_counts()}")
        return self

    # ── Cleaning Helpers ──────────────────────────────────────────────────────

    def _rm_emojis(self, t: str) -> str:
        """Remove all emojis using unicode code point ranges + category fallback"""
        cleaned = []
        for char in t:
            cp = ord(char)
            if (
                0x1F600 <= cp <= 0x1F64F or
                0x1F300 <= cp <= 0x1F5FF or
                0x1F680 <= cp <= 0x1F6FF or
                0x1F700 <= cp <= 0x1F77F or
                0x1F780 <= cp <= 0x1F7FF or
                0x1F800 <= cp <= 0x1F8FF or
                0x1F900 <= cp <= 0x1F9FF or
                0x1FA00 <= cp <= 0x1FA6F or
                0x1FA70 <= cp <= 0x1FAFF or
                0x2600  <= cp <= 0x26FF  or
                0x2700  <= cp <= 0x27BF  or
                0x2300  <= cp <= 0x23FF  or
                0x2B50  <= cp <= 0x2B55  or
                0x25AA  <= cp <= 0x25FE  or
                0x1F1E0 <= cp <= 0x1F1FF or
                0x1F100 <= cp <= 0x1F1FF or
                0x1F200 <= cp <= 0x1F2FF or
                0x1F000 <= cp <= 0x1F02F or
                0x1F0A0 <= cp <= 0x1F0FF or
                0xFE00  <= cp <= 0xFE0F  or
                0x1F3FB <= cp <= 0x1F3FF or
                0x2702  <= cp <= 0x27B0  or
                cp == 0x200D             or
                cp == 0xFE0F             or
                cp == 0x00A9             or
                cp == 0x00AE             or
                cp == 0x2122             or
                cp == 0x3030             or
                cp == 0x303D             or
                cp == 0x3297             or
                cp == 0x3299             or
                unicodedata.category(char) in ('So', 'Sk')
            ):
                continue
            cleaned.append(char)
        return ''.join(cleaned)

    def _rm_zero_width(self, t: str) -> str:
        return re.sub(r'[\u200c-\u200f\u202a-\u202f\u2066-\u2069]', '', t)

    def _rm_urls(self, t: str) -> str:
    # Remove ALL urls aggressively
        t = re.sub(r'http[s]?://\S+', ' ', t)
        t = re.sub(r'www\.\S+', ' ', t)
        t = re.sub(r't\.co/\S+', ' ', t)           # ← Twitter short URLs
        t = re.sub(r'\b\S+\.co\.np\S*', ' ', t)    # ← Nepali domains
        t = re.sub(r'\b\S+\.(com|org|net|io|gov|edu|co|info|biz|np|me|tv)\S*',
                ' ', t, flags=re.IGNORECASE)
        return re.sub(r'\s+', ' ', t).strip()

    def _rm_mentions(self, t: str) -> str:
        t = re.sub(r'@\S*', '', t)
        return re.sub(r'\s+', ' ', t).strip()

    def _rm_hashtags(self, t: str) -> str:
        t = re.sub(r'#\S*', '', t)
        return re.sub(r'\s+', ' ', t).strip()

    def _rm_noise_chars(self, t: str, noise: str) -> str:
        t = t.lower()
        for char in noise:
            t = t.replace(char, ' ')
        return re.sub(r'\s+', ' ', t).strip()

    def _rm_special_chars(self, t: str) -> str:
        t = re.sub(r'[^\u0900-\u097Fa-zA-Z0-9\s]', ' ', t)
        return re.sub(r'\s+', ' ', t).strip()

    def _rm_stopwords(self, t: str, stop_words: List[str]) -> str:
        words = t.split()
        words = [w for w in words if len(w) > 1 and w not in stop_words]
        return ' '.join(words)

    # ── Core Preprocessor ─────────────────────────────────────────────────────

    def preprocess_tweet(self, tweet: str, noise: str, stop_words: List[str]) -> str:
        if tweet is None or str(tweet).strip() in ('', 'nan'):
            return ''

        t = str(tweet)
        t = self._rm_emojis(t)
        t = self._rm_zero_width(t)
        t = self._rm_urls(t)
        t = self._rm_mentions(t)
        t = self._rm_hashtags(t)
        t = self._rm_noise_chars(t, noise)
        t = self._rm_special_chars(t)
        t = self._rm_stopwords(t, stop_words)

        if self.old_vocab_path is None:
            for word in t.split():
                self.vocab[word] = self.vocab.get(word, 0) + 1

        return t.strip()

    # ── Main Cleaner ──────────────────────────────────────────────────────────

    def data_clean(self, stopwords_path: str, apply_filter: bool = False):
        noise = r'~؟॥"▬`%´•●=+÷।–][{}*"_…' + r"''\/" + ';@abcdefghijklmnopqrstuvwxyz1234567890०१२३४५६७८९()-.|!?",:—?।' + "'"

        with open(stopwords_path, encoding='utf-8') as fp:
            stop_words = [line.strip() for line in fp.readlines()]

        if apply_filter and self.filter_words and len(self.filter_words) > 0:
            stop_words += self.filter_words

        # Apply preprocessing
        self.data['clean_text'] = self.data['text'].apply(
            lambda x: self.preprocess_tweet(x, noise, stop_words)
        )

        # Drop duplicates and empty rows
        self.data = self.data.drop_duplicates(subset=['clean_text'])
        self.data = self.data[self.data['clean_text'].str.strip() != '']
        self.data = self.data.reset_index(drop=True)

        # Sort vocab
        self.vocab = dict(sorted(self.vocab.items(), key=lambda x: x[1]))

        # Apply filter words if needed
        if apply_filter:
            if not self.filter_words or len(self.filter_words) == 0:
                less_freq_words = [k for k, v in self.vocab.items() if v < self.min_count]
                huge_words      = [k for k in self.vocab.keys() if len(k) > self.max_word_len]
                self.filter_words = less_freq_words + huge_words

                self.data['clean_text'] = self.data['clean_text'].apply(
                    lambda x: self.filter_txt(x, self.filter_words)
                )
                self.vocab = {k: v for k, v in self.vocab.items()
                              if k not in self.filter_words}

        if self.filter_words:
            self.vocab = {k: v for k, v in self.vocab.items()
                          if k not in self.filter_words}

        # Remove rows with too few words
        self.data = self.data[
            self.data['clean_text'].apply(
                lambda x: len(x.strip().split()) >= self.min_word_needed
            )
        ]
        self.data = self.data.reset_index(drop=True)

        print(f"Cleaned data: {len(self.data)} rows | Vocab size: {len(self.vocab)}")
        print(f"Label Counts:\n{self.data['label'].value_counts()}")
        return self

    # ── Filter Text ───────────────────────────────────────────────────────────

    def filter_txt(self, text, filter_words):
        words = text.split()
        words = [w for w in words if w not in filter_words]
        return ' '.join(words)

    # ── Save Output ───────────────────────────────────────────────────────────

    def save(self, output_path: str):
        self.data[['text', 'label', 'clean_text']].to_csv(output_path, index=False)
        print(f"Saved {len(self.data)} rows to {output_path}")
        return self

    def __iter__(self):
        for _, row in self.data.iterrows():
            yield row['clean_text'].split(' ')

In [33]:
handler = DataHandler(root='.')

# Pass your already loaded dataframe directly
handler.data = data  # your existing dataframe

handler.data_clean(stopwords_path='stop_words_nepali.txt') \
       .save('cleaned_data.csv')

# Preview
handler.data[['text', 'label', 'clean_text']].sample(5)

Cleaned data: 71761 rows | Vocab size: 118636
Label Counts:
label
1.0    44954
2.0    26807
Name: count, dtype: int64
Saved 71761 rows to cleaned_data.csv

,text,label,clean_text
43948,म पनि कुनै जादु होला र मेयर हौला भनेर ढुक्क छु...,1.0,जादु मेयर हौला ढुक्क
23320,बालेन्द्र साहलाई महेश बस्नेतको चेतावनी – ‘तिम्...,1.0,बालेन्द्र साहलाई महेश बस्नेतको चेतावनी समर्थकस...
3216,@NepalPoliceHQ \n@ShahBaalen \nअनलाईन प्रहरी च...,2.0,अनलाईन प्रहरी चारीत्रिक प्रमाणपत्र प्रणालीमा ल...
24253,@Dhruba3626 @bishodip त्यसको समाधान खोज्न पऱ्य...,1.0,समाधान खोज्न पऱ्यो उसो उम्मेद्वारी थोपर्नु प्र...
28756,तेश्राे मधेस अान्दोलन ताका भारत वाट गरिएको नाक...,1.0,तेश्राे मधेस अान्दोलन ताका भारत गरिएको नाकाबन्...

In [34]:
handler.data[['text', 'label', 'clean_text']].sample(10)

,text,label,clean_text
62343,१० पटकभन्दा बढी मतदान ८० वर्षे बृद्धको अनुभव :...,2.0,पटकभन्दा मतदान वर्षे बृद्धको अनुभव बाचा भुल्छन...
66545,स्थानीय तह निर्वाचन: देशभर ३५३ जना निर्विरोध न...,1.0,स्थानीय तह निर्वाचन देशभर निर्विरोध निर्वाचित
48074,"निष्कर्ष: राम्रो जन प्रतिनिधि चयन गर्न , कि त ...",1.0,निष्कर्ष प्रतिनिधि चयन जनप्रतिनिधिलाई नैतिकताम...
456,नाफिजको कार्यसमिति सदस्य पदमा उम्मेदवारी घोषणा...,1.0,नाफिजको कार्यसमिति सदस्य पदमा उम्मेदवारी घोषणा...
39613,केही स्थानका त मतदान स्थगित भएकोछ अनि ६०लाख मत...,1.0,स्थानका मतदान स्थगित भएकोछ मतदाता विदेशमा सुरक...
34554,चितवन को सभापति राजेश्वर खनाल लाई ठुलो मौका थि...,1.0,चितवन सभापति राजेश्वर खनाल ठुलो मौका विद्रोह म...
65751,अनि यताको कान कटुवा भाइ त मेयरमा लौरोलाई र उपम...,2.0,यताको कान कटुवा भाइ मेयरमा लौरोलाई उपमेयरमा कल...
62522,मित्रता को अनुपम नमुना : \nयो हेर्दा साधारण ला...,1.0,मित्रता अनुपम नमुना हेर्दा साधारण लाग्ला फोटोल...
7599,दाङ ३ (ख) मा माओवादी केन्द्रका मास्की विजयी ht...,1.0,दाङ माओवादी केन्द्रका मास्की विजयी
17317,काठमाडौँ महानगरपालिकाको मेयरमा स्वतन्त्र उम्मे...,1.0,काठमाडौँ महानगरपालिकाको मेयरमा स्वतन्त्र उम्मे...

In [35]:
handler.data.info()

<class 'pandas.DataFrame'>
RangeIndex: 71761 entries, 0 to 71760
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   text        71761 non-null  str
 1   label       71761 non-null  float64
 2   clean_text  71761 non-null  str
dtypes: float64(1), str(2)
memory usage: 44.0 MB

In [ ]:
# Keep only clean_text and label
final_df = handler.data[['clean_text', 'label']].copy()

# Rename clean_text -> text
final_df = final_df.rename(columns={'clean_text': 'text'})

# Save CSV
final_df.to_csv('cleaned_dataset_3label.csv', index=False, encoding='utf-8-sig')

print("Saved cleaned dataset successfully.")

Saved cleaned dataset successfully.